version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: trading_postgres
    environment:
      POSTGRES_DB: trading_platform
      POSTGRES_USER: trading_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trading_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache and Queue
  redis:
    image: redis:7-alpine
    container_name: trading_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Trading Engine (Python)
  trading_engine:
    build:
      context: ./backend/trading_engine
      dockerfile: Dockerfile
    container_name: trading_engine
    environment:
      DATABASE_URL: postgresql://trading_user:${POSTGRES_PASSWORD:-changeme}@postgres:5432/trading_platform
      REDIS_URL: redis://redis:6379
      ALPACA_API_KEY: ${ALPACA_API_KEY}
      ALPACA_SECRET_KEY: ${ALPACA_SECRET_KEY}
      POLYGON_API_KEY: ${POLYGON_API_KEY}
      NEWS_API_KEY: ${NEWS_API_KEY}
      TRADING_MODE: ${TRADING_MODE:-paper}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend/trading_engine:/app
      - ./logs:/app/logs
    restart: unless-stopped

  # API Gateway (Node.js)
  api_gateway:
    build:
      context: ./backend/api_gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    environment:
      DATABASE_URL: postgresql://trading_user:${POSTGRES_PASSWORD:-changeme}@postgres:5432/trading_platform
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3000
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend/api_gateway:/app
      - ./logs:/app/logs
    restart: unless-stopped

  # Discord Bot (Node.js)
  discord_bot:
    build:
      context: ./backend/discord_bot
      dockerfile: Dockerfile
    container_name: discord_bot
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
      API_GATEWAY_URL: http://api_gateway:3000
      REDIS_URL: redis://redis:6379
      NODE_ENV: production
    depends_on:
      - api_gateway
      - redis
    volumes:
      - ./backend/discord_bot:/app
      - ./logs:/app/logs
    restart: unless-stopped

  # Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: trading_frontend
    environment:
      REACT_APP_API_URL: http://localhost:3000
      REACT_APP_WS_URL: ws://localhost:3000
    ports:
      - "80:80"
    depends_on:
      - api_gateway
    restart: unless-stopped

  # Prometheus (Monitoring)
  prometheus:
    image: prom/prometheus:latest
    container_name: trading_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped

  # Grafana (Visualization)
  grafana:
    image: grafana/grafana:latest
    container_name: trading_grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  default:
    name: trading_network
